source 'https://rubygems.org'

gem 'pry'
gem 'sinatra', '~> 2.0'
gem 'rerun'
gem 'pg', '~> 0.20'
gem 'thin', '~> 1.7'
gem 'sequel', '~> 4.47'
gem 'pry-byebug'
gem 'rake'
gem 'minitest'
gem 'rack-test'
gem 'faye-websocket'
